name: cd_docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo "RELEASE_VERSION=${GITHUB_REF:10}" >> "$GITHUB_ENV"
    - uses: tradeshift/actions-docker@v1
      with:
        password: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_NOBASE64 }}
        useqemu: true
        platform: linux/amd64,linux/arm64
